# Generated by Django 5.1 on 2024-10-29 18:30

import user.models.user
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_profile_options_alter_profile_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=user.models.user.user_directory_path),
        ),
    ]
