# Generated by Django 4.2.5 on 2025-03-06 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('phase', models.CharField(choices=[('Engage', 'Engage'), ('Act', 'Act'), ('Investigate', 'Investigate')], max_length=20)),
                ('dynamic_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='project.project')),
            ],
        ),
    ]
