# Generated by Django 4.2.5 on 2025-09-30 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_page_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='blocks',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
