# Generated by Django 4.2.5 on 2025-11-29 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
        ('page', '0003_page_blocks'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='page',
            unique_together={('project', 'phase', 'order')},
        ),
    ]
