# Generated by Django 4.2.5 on 2025-12-14 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_page_html_alter_page_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
