# Generated by Django 4.2.5 on 2025-12-14 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_remove_page_email_page_html_page_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='email',
        ),
        migrations.AddField(
            model_name='page',
            name='html',
            field=models.TextField(blank=True),
        ),
    ]
