# Generated by Django 4.2.5 on 2025-12-16 16:18

from django.db import migrations

FORWARDS_SQL = r"""
-- 1) Se existir phase_id, drope.
SET @col_exists := (
  SELECT COUNT(*)
  FROM information_schema.columns
  WHERE table_schema = DATABASE()
    AND table_name = 'page_page'
    AND column_name = 'phase_id'
);

SET @sql := IF(@col_exists > 0,
  'ALTER TABLE page_page DROP COLUMN phase_id',
  'SELECT 1'
);

PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

-- 2) Se NÃO existir phase_id, adicione como BIGINT NULL.
SET @col_exists2 := (
  SELECT COUNT(*)
  FROM information_schema.columns
  WHERE table_schema = DATABASE()
    AND table_name = 'page_page'
    AND column_name = 'phase_id'
);

SET @sql2 := IF(@col_exists2 = 0,
  'ALTER TABLE page_page ADD COLUMN phase_id BIGINT NULL',
  'SELECT 1'
);

PREPARE stmt2 FROM @sql2;
EXECUTE stmt2;
DEALLOCATE PREPARE stmt2;

-- 3) Se NÃO existir índice, crie.
SET @idx_exists := (
  SELECT COUNT(*)
  FROM information_schema.statistics
  WHERE table_schema = DATABASE()
    AND table_name = 'page_page'
    AND index_name = 'page_page_phase_id_idx'
);

SET @sql3 := IF(@idx_exists = 0,
  'CREATE INDEX page_page_phase_id_idx ON page_page (phase_id)',
  'SELECT 1'
);

PREPARE stmt3 FROM @sql3;
EXECUTE stmt3;
DEALLOCATE PREPARE stmt3;
"""

REVERSE_SQL = r"""
-- reverse 1) Se existir índice, drope.
SET @idx_exists := (
  SELECT COUNT(*)
  FROM information_schema.statistics
  WHERE table_schema = DATABASE()
    AND table_name = 'page_page'
    AND index_name = 'page_page_phase_id_idx'
);

SET @sql := IF(@idx_exists > 0,
  'DROP INDEX page_page_phase_id_idx ON page_page',
  'SELECT 1'
);

PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

-- reverse 2) Se existir phase_id, drope.
SET @col_exists := (
  SELECT COUNT(*)
  FROM information_schema.columns
  WHERE table_schema = DATABASE()
    AND table_name = 'page_page'
    AND column_name = 'phase_id'
);

SET @sql2 := IF(@col_exists > 0,
  'ALTER TABLE page_page DROP COLUMN phase_id',
  'SELECT 1'
);

PREPARE stmt2 FROM @sql2;
EXECUTE stmt2;
DEALLOCATE PREPARE stmt2;

-- reverse 3) Se NÃO existir phase_id, recrie como VARCHAR(20) NOT NULL.
SET @col_exists2 := (
  SELECT COUNT(*)
  FROM information_schema.columns
  WHERE table_schema = DATABASE()
    AND table_name = 'page_page'
    AND column_name = 'phase_id'
);

SET @sql3 := IF(@col_exists2 = 0,
  'ALTER TABLE page_page ADD COLUMN phase_id VARCHAR(20) NOT NULL',
  'SELECT 1'
);

PREPARE stmt3 FROM @sql3;
EXECUTE stmt3;
DEALLOCATE PREPARE stmt3;
"""

def forwards(apps, schema_editor):
    # This migration is MySQL-specific (information_schema, DATABASE(), PREPARE/EXECUTE, SET variables).
    if schema_editor.connection.vendor != "mysql":
        return
    schema_editor.execute(FORWARDS_SQL)

def backwards(apps, schema_editor):
    if schema_editor.connection.vendor != "mysql":
        return
    schema_editor.execute(REVERSE_SQL)

class Migration(migrations.Migration):

    dependencies = [
        ("page", "0006_remove_page_email_page_html"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]