# Generated by Django 4.2.5 on 2025-12-16 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0007_mysql_fix_phase_columns'),
        ("phase", "0005_remove_phase_key_remove_phase_label_phase_project"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # Banco já está no estado certo (phase_name varchar, phase_id bigint).
                # Não execute nada aqui.
            ],
            state_operations=[
                # No estado do Django, o campo antigo era "phase" (CharField).
                # Renomeamos para phase_name.
                migrations.RenameField(
                    model_name="page",
                    old_name="phase",
                    new_name="phase_name",
                ),
                # E adicionamos o novo FK "phase" apontando para a coluna phase_id já existente.
                migrations.AddField(
                    model_name="page",
                    name="phase",
                    field=models.ForeignKey(
                        to="phase.phase",
                        null=True,
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        db_column="phase_id",
                    ),
                ),
            ],
        ),
    ]
