# Generated by Django 4.2.5 on 2025-12-16 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_remove_project_email_project_owner'),
        ('phase', '0005_remove_phase_key_remove_phase_label_phase_project'),
        ('page', '0008_sync_state_with_mysql_phase_columns'),
    ]

    operations = [
        # migrations.AlterUniqueTogether(
        #     name='page',
        #     unique_together={('phase', 'order')},
        # ),
        migrations.AlterField(
            model_name='page',
            name='phase_name',
            field=models.CharField(choices=[('Engage', 'Engage'), ('Act', 'Act'), ('Investigate', 'Investigate')], db_column='phase_name', max_length=20),
        ),
        migrations.AlterField(
            model_name='page',
            name='project',
            field=models.ForeignKey(blank=True, db_column='project_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='project.project'),
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['phase', 'order'], name='page_page_phase_i_61d90b_idx'),
        ),
    ]
