# Generated by Django 4.2.5 on 2025-12-18 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_remove_project_email_project_owner'),
        ('phase', '0006_alter_phase_name_alter_phase_unique_together'),
        ('page', '0009_alter_page_unique_together_alter_page_phase_name_and_more'),
    ]

    operations = [
        # migrations.AlterUniqueTogether(
        #     name='page',
        #     unique_together=set(),
        # ),
        migrations.AlterField(
            model_name='page',
            name='phase',
            field=models.ForeignKey(db_column='phase_id', on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='phase.phase'),
        ),
        migrations.AlterField(
            model_name='page',
            name='project',
            field=models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='project.project'),
        ),
        migrations.AddConstraint(
            model_name='page',
            constraint=models.UniqueConstraint(fields=('phase', 'order'), name='uq_page_phase_order'),
        ),
    ]
