# Generated by Django 4.2.5 on 2025-12-18 14:33

from django.db import migrations

FORWARDS_SQL = r"""
SET @idx := (
  SELECT INDEX_NAME
  FROM information_schema.statistics
  WHERE table_schema = DATABASE()
    AND table_name = 'page_page'
    AND index_name = 'page_page_phase_i_61d90b_idx'
  LIMIT 1
);
SET @sql := IF(@idx IS NULL, 'SELECT 1', CONCAT('ALTER TABLE page_page DROP INDEX ', @idx));
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;
"""

def forwards(apps, schema_editor):
    # MySQL-only migration: uses information_schema, DATABASE(), SET vars, PREPARE/EXECUTE.
    if schema_editor.connection.vendor != "mysql":
        return
    schema_editor.execute(FORWARDS_SQL)

def backwards(apps, schema_editor):
    # reverse_sql was "SELECT 1;" originally, keep as no-op.
    return

class Migration(migrations.Migration):

    dependencies = [
        ("page", "0010_alter_page_unique_together_alter_page_phase_and_more"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
        # migrations.AlterUniqueTogether(
        #     name='page',
        #     unique_together=set(),
        # ),
    ]