# Generated by Django 4.2.5 on 2025-12-23 20:22

from django.db import migrations, models
import django.db.models.deletion
import page.models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0011_remove_page_page_page_phase_i_61d90b_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to=page.models.page_image_upload_to)),
                ('size', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='pageimage',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='page.page'),
        ),
    ]
