# Generated by Django 4.2.5 on 2025-12-23 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0012_pageimage_remove_page_page_page_phase_i_61d90b_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageimage',
            name='page',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='images',
                to='page.page',
            ),
        ),

    ]
