# Generated by Django 4.2.5 on 2025-12-26 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('page', '0013_add_page_fk_to_pageimage'),
    ]

    operations = [
        # migrations.RemoveIndex(
        #     model_name='page',
        #     name='page_page_phase_i_61d90b_idx',
        # ),
        # migrations.AlterUniqueTogether(
        #     name='page',
        #     unique_together=set(),
        # ),
        migrations.AddField(
            model_name='page',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_pages', to=settings.AUTH_USER_MODEL),
        ),
    ]
