# Generated by Django 4.2.27 on 2026-01-19 15:47

from django.db import migrations

DROP_UQ_IF_EXISTS = r"""
SET @idx := (
  SELECT COUNT(1)
  FROM information_schema.statistics
  WHERE table_schema = DATABASE()
    AND table_name = 'page_page'
    AND index_name = 'uq_page_phase_order'
);
SET @sql := IF(
  @idx > 0,
  'DROP INDEX `uq_page_phase_order` ON `page_page`',
  'SELECT 1'
);
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;
"""

DROP_INDEX_IF_EXISTS = r"""
SET @idx := (
  SELECT COUNT(1)
  FROM information_schema.statistics
  WHERE table_schema = DATABASE()
    AND table_name = 'page_page'
    AND index_name = 'page_page_phase_i_61d90b_idx'
);
SET @sql := IF(
  @idx > 0,
  'DROP INDEX `page_page_phase_i_61d90b_idx` ON `page_page`',
  'SELECT 1'
);
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;
"""

def drop_uq_forward(apps, schema_editor):
    if schema_editor.connection.vendor != "mysql":
        return
    schema_editor.execute(DROP_UQ_IF_EXISTS)

def drop_uq_backward(apps, schema_editor):
    # previously reverse_sql=noop
    return

def drop_index_forward(apps, schema_editor):
    if schema_editor.connection.vendor != "mysql":
        return
    schema_editor.execute(DROP_INDEX_IF_EXISTS)

def drop_index_backward(apps, schema_editor):
    # previously reverse_sql=noop
    return

class Migration(migrations.Migration):

    dependencies = [
        ("page", "0014_remove_page_page_page_phase_i_61d90b_idx_and_more"),
    ]

    operations = [
        migrations.RunPython(drop_uq_forward, drop_uq_backward),
        migrations.RunPython(drop_index_forward, drop_index_backward),
    ]