# Generated by Django 4.2.27 on 2026-02-10 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0016_remove_page_uq_page_phase_order_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='page',
            name='uq_page_phase_order',
        ),
        migrations.RemoveIndex(
            model_name='page',
            name='page_page_phase_i_61d90b_idx',
        ),
    ]
