# Generated by Django 4.2.28 on 2026-02-26 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0015_remove_page_uq_page_phase_order_and_more'),
        ('page', '0017_remove_page_uq_page_phase_order_and_more'),
    ]

    operations = [
    ]
