# Generated by Django 4.2.28 on 2026-02-26 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_project_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
    ]
