# Generated by Django 4.2.5 on 2025-01-30 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=2056)),
                ('icon', models.ImageField(default='Sem Icone', upload_to='media/images/')),
                ('component_map', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
