# Generated by Django 4.2.5 on 2025-02-06 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phase', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Phase',
        ),
    ]
