# Generated by Django 4.2.5 on 2025-03-06 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('phase', '0002_delete_phase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('Engage', 'Engage'), ('Investigate', 'Investigate'), ('Act', 'Act')], max_length=20)),
                ('step', models.CharField(max_length=50)),
                ('content', models.TextField(blank=True, default='')),
                ('description', models.TextField(max_length=2056)),
                ('icon', models.ImageField(default='Sem Icone', upload_to='media/images/')),
            ],
        ),
    ]
