# Generated by Django 4.2.5 on 2025-12-14 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phase', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phase',
            old_name='step',
            new_name='key',
        ),
        migrations.RemoveField(
            model_name='phase',
            name='content',
        ),
        migrations.RemoveField(
            model_name='phase',
            name='phase',
        ),
        migrations.AddField(
            model_name='phase',
            name='label',
            field=models.CharField(default='LEGADO', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phase',
            name='name',
            field=models.CharField(choices=[('Engage', 'Engage'), ('Investigate', 'Investigate'), ('Act', 'Act')], default='LEGADO', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phase',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
