# Generated by Django 4.2.5 on 2025-12-16 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_remove_project_email_project_owner'),
        ('phase', '0004_rename_step_phase_key_remove_phase_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phase',
            name='key',
        ),
        migrations.RemoveField(
            model_name='phase',
            name='label',
        ),
        migrations.AddField(
            model_name='phase',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='project.project'),
        ),
    ]
