# Generated by Django 4.2.5 on 2025-12-16 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_remove_project_email_project_owner'),
        ('phase', '0005_remove_phase_key_remove_phase_label_phase_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phase',
            name='name',
            field=models.CharField(choices=[('Engage', 'Engage'), ('Investigate', 'Investigate'), ('Act', 'Act')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='phase',
            unique_together={('project', 'name')},
        ),
    ]
