# Generated by Django 4.2.5 on 2025-12-21 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phase', '0006_alter_phase_name_alter_phase_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='phase',
            name='index',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
