# Generated by Django 4.2.5 on 2025-12-21 15:16

from django.db import migrations

def copy_order_to_index(apps, schema_editor):
    Phase = apps.get_model('phase', 'Phase')
    for phase in Phase.objects.all():
        phase.index = phase.order
        phase.save(update_fields=['index'])

class Migration(migrations.Migration):

    dependencies = [
        ('phase', '0007_phase_index'),
    ]

    operations = [
        migrations.RunPython(copy_order_to_index),
    ]
