# Generated by Django 4.2.5 on 2025-12-21 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phase', '0008_migrate_order_to_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phase',
            name='order',
        ),
    ]
