# Generated by Django 4.2.5 on 2025-12-14 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('page', '0005_remove_page_email_page_html_page_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='concept/icons/')),
                ('order', models.PositiveIntegerField()),
                ('label', models.CharField(max_length=255)),
                ('content', models.JSONField(blank=True, default=list)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concepts', to='page.page')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('page', 'key')},
            },
        ),
    ]
