# Generated by Django 4.2.5 on 2025-12-14 18:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('concept', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='concept',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='concept',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='concept',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddConstraint(
            model_name='concept',
            constraint=models.UniqueConstraint(fields=('page', 'key'), name='uq_concept_page_key'),
        ),
        migrations.AddConstraint(
            model_name='concept',
            constraint=models.UniqueConstraint(fields=('page', 'order'), name='uq_concept_page_order'),
        ),
    ]
